//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaiBaoYTe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.CauTraLoi_ChiTiet = new HashSet<CauTraLoi_ChiTiet>();
            this.Sub_CauHoi = new HashSet<Sub_CauHoi>();
        }
    
        public int IDCauHoi { get; set; }
        public Nullable<int> IDTemplate { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> IDLoaiCauHoi { get; set; }
        public bool CauHoiRequired { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public string NguoiUpdate { get; set; }
        public Nullable<int> SoDiem { get; set; }
        public Nullable<bool> CauHoiEnable { get; set; }
    
        public virtual LoaiCauHoi LoaiCauHoi { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauTraLoi_ChiTiet> CauTraLoi_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_CauHoi> Sub_CauHoi { get; set; }
    }
}
