//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaiBaoYTe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauTraLoiDung
    {
        public Nullable<int> IDCauHoi { get; set; }
        public string CauTraLoi_Dung { get; set; }
        public int ID_CTL_Dung { get; set; }
    }
}
