//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaiBaoYTe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauTraLoi_ChiTiet
    {
        public int IDCauTraLoiChiTiet { get; set; }
        public Nullable<int> IDCauTraLoi { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public string CauTraLoi { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual CauTraLoi CauTraLoi1 { get; set; }
    }
}
