//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaiBaoYTe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauTraLoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauTraLoi()
        {
            this.CauTraLoi_ChiTiet = new HashSet<CauTraLoi_ChiTiet>();
        }
    
        public int IDCauTraLoi { get; set; }
        public Nullable<int> UserID { get; set; }
        public string HoTen { get; set; }
        public string MSNV { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDChuDe { get; set; }
        public Nullable<int> IDTemplate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauTraLoi_ChiTiet> CauTraLoi_ChiTiet { get; set; }
        public virtual ChuDe ChuDe { get; set; }
        public virtual Template Template { get; set; }
    }
}
