//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaiBaoYTe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_CauHoi
    {
        public int IDSubCauHoi { get; set; }
        public Nullable<int> IDCauHoi { get; set; }
        public string NoiDung { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
